### ISSUE TITLE
Improve Visibility On StubMappings Mismatch

### ISSUE THREAD

**Issue by michaelmcfadyen** [datastax/simulacron#102]
Currently, if you were to wrongly prime simulacron for a query you are returned an exhausted result set. There is no indication in the logs from simulacron that anything has went wrong or that no stubbing has been found. This can lead to an increased time for the developer to investigate, identify their mistake and rectify it (this has happened to me).

My initial thoughts on improving this would be to log a statement saying that no stub mapping was found for this query. From a quick look at the code, I can see that there are default responses for each of the message types. In this case, we may not want to have this log for all message types ie. (STARTUP/REGISTER) but it could be very useful for other types (QUERY/EXECUTE/PREPARE/BATCH).

**Comment by adutra** [comment]
I agree that this would be extremely helpful. My initial thought was that we probably already have this feature, it would just be a matter of setting the level of logger `com.datastax.oss.simulacron` to DEBUG. But a quick check in the code shows that log messages are very scarce :-(
So in short: yes, more log messages, especially when a query doesn't match a stub mapping, would be great.

**Comment by joao-r-reis** [comment]
I had this issue a couple of times already so +1 from me on logging something when there is no match (and more log messages in general)

**Comment by michaelmcfadyen** [comment]
Do we agree that this logging is only useful on a subset of the message types? For STARTUP, REGISTER and OPTIONS I can see this log leading to more confusion as I'm assuming most people don't set custom primings for these message types and as a result the default is used in most cases.
