### ISSUE TITLE
Timeline For 0.11.0 Release

### ISSUE THREAD

**Issue by michaelmcfadyen** [datastax/simulacron#107]
Currently there is no due date on the 0.11.0 milestone and there are some useful features in master (specifically #103 ) that are part of the 0.11.0 milestone that have not been released yet. 

What is the current plan/timeframe for releasing 0.11.0?

**Comment by adutra** [comment]
Hi, there is a plan to release 0.11.0 next month, stay tuned!

**Comment by michaelmcfadyen** [comment]
Great news, thanks! 🎉

**Comment by adutra** [comment]
0.11.0 released today!
