### ISSUE TITLE
Expose protocol version in query logs

### ISSUE THREAD

**Issue by olim7t** [datastax/simulacron#5]
This will be useful for protocol negotiation tests (such as `ProtocolVersionMixedClusterIT` in Java driver 4).

**Comment by tolbertam** [comment]
👍 .  Thinking about this I'd like to refactor the query logs so they include comprehensive information about both the frame and the underlying message which would include the protocol versions, protocol flags and message specific data.  This will require implementing jackson de/serializers for each native protocol message which could let us do cool things like extract native protocol messages from the query log itself.  To get things started, I could also just attach the underlying Frame to existing query logs, which would help the java API only.
