### ISSUE TITLE
Parameters in logs may contain information from other queries

### ISSUE THREAD

**Issue by jorgebay** [datastax/simulacron#74]
I'm currently executing the same QUERY request twice, with different parameters.

For example:
- Query: `SELECT * FROM table WHERE key = ?`
- First request params:` [ "abcdef" ]`
- Second request params: `[ "zzz" ]`

When I obtain the logs, inside `frame.message.options.positional_values` it returns:
- `"abcdef"` for the first execution
- `"zzzdef"` for the second execution

It's probably related to buffer/resource pooling.

**Comment by tolbertam** [comment]
Ack - good catch, I'll look into this, thanks for the heads up!
