### ISSUE TITLE
Please publish 0.8.11 to maven central

### ISSUE THREAD

**Issue by chapj2001** [datastax/simulacron#88]
Pretty sure I need simulacron 0.8.11's [commit 012c8d0](https://github.com/datastax/simulacron/commit/012c8d0f6bc37c717d4109ab67539750da4ee309) case insensitivity change to fix a connection failure in my tests when updating to DataStax Java driver 3.7.2, but maven central's latest simulacron version is 0.8.10.

**Comment by adutra** [comment]
@chapj2001 I just pushed 0.9 and 0.10 to Maven Central, is that enough for you or do you absolutely need 0.8.11? Thanks!
