### ISSUE TITLE
Prepared statement match has bug matching the parameters. 

### ISSUE THREAD

**Issue by cthumuluru** [datastax/simulacron#98]
With Simulacron, while mocking prepared statements with more than one parameters of different types, our tests are failing. I think it's a bug in the way the parameter metadata is stored and checked for a match. 

Parameter types and values are two different maps (API doesn't enforce ordered maps) and the match fails. The bug is in the following code (`com.datastax.oss.simulacron.common.request.Query`) where the iterators won't yield elements in the matching order:
`

        Iterator<Object> primedPositionValues = params.values().iterator();
        Iterator<String> primedPositionTypes = paramTypes.values().iterator();
        // iterate over the parameters and make sure they all match
        for (ByteBuffer buffer : options.positionalValues) {
          if (!checkParamsEqual(
              buffer, primedPositionValues.next(), primedPositionTypes.next(), mapper)) {
            return false;
          }
        }
`
Replacing Map with LinkedHashMap fixes the issue.

**Comment by cthumuluru** [comment]
I can work on a fix if someone assert my findings.

**Comment by jorgebay** [comment]
Nice findings!

Feel free to submit a patch, I can review it :)

**Comment by cthumuluru** [comment]
@jorgebay — Can you please review this [PR](https://github.com/datastax/simulacron/pull/99) and provide your feedback? 

In `Query.java` I think it would be nice to compare the column positions and throw `RuntimeException` if the param order won't match. I didn't add it in this PR since the existing code was not doing it either. :) 

Also, ResultSet suffers from similar ordering issues. I'll send those changes in a different PR.

**Comment by cthumuluru** [comment]
Added changes to retain the order of column values in a Row.
